#LTS and lightweight
FROM node:20-alpine

WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

COPY . .

# Expose the default Vite port
EXPOSE 5173

# Start the Vite development server. 
# The "--host" flag ensures the server listens on all network interfaces, 
# making it accessible from outside the Docker container.
CMD ["npm", "run", "dev", "--", "--host"]
